var a = Math.random()
console.log(a)

var a = Math.floor(1.5)
console.log(a)
var a = Math.floor(1.9)
console.log(a)
var a = Math.floor(2.2)
console.log(a)
var a = Math.floor(-1.5)
console.log(a)
var a = Math.floor(-1.9)
console.log(a)
var a = Math.floor(-2.2)
console.log(a)